#!/bin/bash

# Project Structure Overview
# Shows the organized file and folder structure

echo "📁 Patricia & James Wedding App - Project Structure"
echo "=================================================="
echo ""

echo "📂 Root Directory:"
echo "├── 📄 README.md                    # Main project documentation"
echo "├── 🗄️ db                           # Database management tool"
echo "├── 📁 client/                      # Frontend application"
echo "├── 📁 server/                      # Backend application"
echo "├── 📁 scripts/                     # Database and utility scripts"
echo "└── 📁 docs/                        # Project documentation"
echo ""

echo "📂 scripts/ - Database Management:"
echo "├── 🧹 quick-clean.sh              # Remove test data, keep seeded users"
echo "├── 🗑️ clear-rsvps.sh              # Clear all RSVPs"
echo "├── 👥 clear-test-users.sh         # Remove test users"
echo "├── 🔄 reset-to-seed.sh            # Complete reset to seeded state"
echo "├── 🛠️ db-tools.sh                 # Overview of all database tools"
echo "└── 🔧 check-system.sh             # System health check"
echo ""

echo "📂 docs/ - Documentation:"
echo "├── 📋 PROJECT_PLAN.md              # Project planning and status"
echo "├── 🔧 ADMIN_GUIDE.md               # Admin user setup guide"
echo "├── 🗄️ DATABASE_SCHEMA.md           # Database schema documentation"
echo "├── 🧹 CLEANUP_STRATEGY.md          # Code cleanup strategy"
echo "└── 🎨 style-guide.md               # Code style guidelines"
echo ""

echo "📂 server/ - Backend Structure:"
echo "├── 📁 src/                        # Source code"
echo "│   ├── 📁 config/                 # Database configuration"
echo "│   ├── 📁 middleware/             # Express middleware"
echo "│   └── 📁 routes/                 # API routes"
echo "├── 📁 admin/                      # Admin scripts"
echo "├── 📁 database/                   # Database migrations"
echo "├── 📁 scripts/                    # Server utilities"
echo "├── 📁 tests/                      # Test suites"
echo "└── 📄 package.json                # Dependencies"
echo ""

echo "📂 client/ - Frontend Structure:"
echo "├── 📁 src/                        # Source files"
echo "│   ├── 📄 index.html              # Main HTML file"
echo "│   ├── 📁 css/                    # Stylesheets"
echo "│   ├── 📁 js/                     # JavaScript files"
echo "│   └── 📁 images/                 # Image assets"
echo "└── 📄 package.json                # Dependencies"
echo ""

echo "🚀 Quick Commands:"
echo "  ./db stats                       # Check database status"
echo "  ./scripts/quick-clean.sh         # Clean test data"
echo "  ./scripts/db-tools.sh            # Show all database tools"
echo "  cd server && npm test            # Run test suite"
echo ""
