-- Migration 011: Create Admin User (James Reynolds)
-- Inserts James as an admin user if not already exists

-- Insert James Reynolds as admin user
-- Password will need to be set via registration
-- Note: full_name is auto-generated by a trigger
INSERT INTO users (
    first_name,
    last_name,
    email,
    is_admin
)
VALUES (
    'James',
    'Reynolds',
    'jameshreynolds@gmail.com',
    true
)
ON CONFLICT (email) DO UPDATE
SET is_admin = true;

-- Verify admin user was created
SELECT
    id,
    email,
    full_name,
    is_admin,
    password_hash IS NOT NULL as has_password
FROM users
WHERE email = 'jameshreynolds@gmail.com';
